//----------------------------------------------------------------
//
//-- ILS Technology
//-- DeviceWISE Core
//
//-- Filename: devicewise/core/errors.h
//
//-- Copyright: 2001-2013, ILS Technology, LLC
//
//----------------------------------------------------------------

#ifndef DW_CORE_ERRORS_H_
#define DW_CORE_ERRORS_H_

// -1100 - -1199 Command Error Codes
#define ERR_CMD_BADPARMS				-1101 // Incorrect Paramanters.
#define ERR_CMD_UNKNOWN					-1102 // Unknown Command Code.
#define ERR_CMD_NOTIMPLIMENTED			-1103 // Command not implemented.
#define ERR_CMD_BADRETPARMS				-1104 // Incorrect Parameters in response.
#define ERR_CMD_NOTLOGGEDIN				-1105 // Not logged in.
#define ERR_CMD_BUSY					-1106 // System busy.
#define ERR_CMD_SEE_EXCEPTION			-1107

#define ERR_API_BAD_JSON				-1121
#define ERR_API_INVALID_COMMAND			-1122
#define ERR_API_INVALID_RESPONSE		-1123
#define ERR_API_SUCCESS_MISSING			-1124
#define ERR_API_BLOCK_NOT_FOUND			-1125
#define ERR_API_BLOCK_ERROR				-1126
#define ERR_API_SEE_MESSAGE				-1127

#define ERR_HTTPSVR_STARTED				-1141
#define ERR_HTTPSVR_STOPPED				-1142
#define ERR_HTTPSVR_MOREDATA			-1143
#define ERR_HTTPSVR_PROTO				-1144
#define ERR_HTTPSVR_BAD_INLINE			-1145
#define ERR_HTTPSVR_UNLICENSED			-1146
#define ERR_HTTPSVR_RESP_DEFERRED		-1147
#define ERR_HTTPSVR_BAD_COOKIE			-1148

#define ERR_DBG_GENDBG_NOT_SUPPORTED	-1161

#define ERR_PLUGIN_BADENTRY				-1201 // Plugin Entry Incorrect.
#define ERR_PLUGIN_BADINSTALL			-1202 // Installation Entry Point Not Found.
#define ERR_PLUGIN_ALREADY_LOADED		-1203 // Plugin has already been loaded.
#define ERR_PLUGIN_CANT_BE_LOADED		-1204 // Plugin can't be loaded.
#define ERR_MODULE_NO_VERSION			-1221 // Module has no version information.
#define ERR_MODULE_LOAD_IN_PROGRESS		-1222 // Modules are currently loading.
#define ERR_SQLITE_DB_NOT_AVAILABLE		-1231 // SQLITE Database is not available.
#define ERR_SQLITE_DB_NO_COLUMNS		-1232

#define ERR_SYSTEM_STARTING				-1241 // System is starting.
#define ERR_SYSTEM_SUSPENDED			-1242 // System is suspended.
#define ERR_SYSTEM_RUNNING				-1243 // System is running.
#define ERR_SYS_DB_LOCKED				-1244
#define ERR_SYS_DB_UNLOCKED				-1245

#define ERR_PROC_BLOCALREADYREG			-1301 // Processor Bloc Already Registered.
#define ERR_FIRMWARE_PROCESS_FAILED		-1302 
#define ERR_FIRMWARE_DECRYPT			-1303
#define ERR_FIRMWARE_HEADER				-1304
#define ERR_FIRMWARE_FILE_OPEN			-1305
#define ERR_FIRMWARE_PRODUCT_MISMATCH	-1306
#define ERR_PROC_TOO_MANY_REGISTRATIONS	-1307
#define ERR_FIRMWARE_TYPE_MISMATCH		-1308
#define ERR_FIRMWARE_PLATFORM_MISMATCH	-1309
#define ERR_FIRMWARE_MINBUILD_MISMATCH	-1310
#define ERR_FIRMWARE_FILE_NOT_FOUND		-1311
#define ERR_PACKAGE_INSTALLER_RUNNING	-1312

#define ERR_LSTNR_BADDEF				-1401 // Listener definition is bad.
#define ERR_SESSION_NOT_FOUND			-1451 // Session not found.
#define ERR_SESSION_REPLY_NOT_COMPLETE	-1452 // Session reply could not be completed.

#define ERR_SEC_MODULE_NOT_LOADED		-1501
#define ERR_SEC_AUTH_FAIL				-1502
#define ERR_SEC_ACCESS_DENIED			-1503
#define ERR_SEC_BADXML					-1506
#define ERR_SEC_OTHER					-1509
#define ERR_SEC_POLICY_EXISTS			-1511
#define ERR_SEC_POLICY_NOT_FOUND		-1512
#define ERR_SEC_POLICY_STARTED			-1513
#define ERR_SEC_POLICY_STOPPED			-1514
#define ERR_SEC_POLICY_SAME_PRIO		-1515
#define ERR_SEC_POLICY_EMPTY			-1516
#define ERR_SEC_CACHE_MISS				-1521
#define ERR_SEC_CACHE_ERROR				-1522
#define ERR_SEC_RESOURCE_EXISTS			-1531
#define ERR_SEC_RESOURCE_HAS_CHILDREN	-1532
#define ERR_SEC_ROLE_EXISTS				-1541
#define ERR_SEC_ROLE_NOT_FOUND			-1542
#define ERR_SEC_ROLE_PROTECTED			-1543
#define ERR_SEC_ROLE_EMPTY				-1544
#define ERR_SEC_USER_EXISTS				-1551
#define ERR_SEC_USER_NOT_FOUND			-1552
#define ERR_SEC_USER_PROTECTED			-1553
#define ERR_SEC_USER_SELF				-1554
#define ERR_SEC_USER_DIS_SELF			-1555
#define ERR_SEC_USER_EMPTY				-1556
#define ERR_SEC_USER_BAD_PASSWORD		-1557

#define ERR_SCHEDULE_BAD_XML			-1604 // Bad Xml.

#define ERR_BRIDGE_BAD_PROTO			-1701
#define ERR_BRIDGE_NOT_CONNECTED		-1702
#define ERR_BRIDGE_REPLY_NOT_COMPLETE	-1703
#define ERR_BRIDGE_TIMEOUT				-1704
#define ERR_BRIDGE_STATUS_CB_NOTFOUND	-1705
#define ERR_BRIDGE_CHANNEL_OBJ_NOTFOUND	-1706
#define ERR_BRIDGE_CHANNEL_OBJ_EXIST	-1707

#define ERR_PERSIST_NOTFOUND			-2001
#define ERR_PERSIST_BAD_TYPE			-2002
#define ERR_PERSIST_BAD_XML				-2003

#define ERR_CHAN_MODULE_NOT_LOADED		-2101
#define ERR_CHAN_NOTFOUND				-2102 // Channel not found.
#define ERR_CHAN_EXISTS					-2103 // Channel already exists.
#define ERR_CHAN_SUBNOTFOUND			-2104 // Subscription not found.
#define ERR_CHAN_HASSUBSCRIPTIONS		-2105 // Channel has existing subscriptions.

#define ERR_SYS_VAR_NOTFOUND			-2201
#define ERR_SYS_VAR_EXISTS				-2202
#define ERR_SYS_VAR_READ_ONLY			-2203
#define ERR_SYS_NOT_AUTHORIZED			-2211
#define ERR_SYS_LOCATION_NOT_SET		-2221

#define ERR_LOGGING_BAD_XML				-2301 // BAD XML.
#define ERR_LOGGING_NLS_NOT_FOUND		-2302 // Error.nls file not found.
#define ERR_LOGGING_SQL_FAILED			-2303 // Sqlite Select failed.
#define ERR_LOGGING_BAD_FILENAME		-2304 // Bad filename to dump on.
#define ERR_LOGGING_BAD_RETURN			-2305 
#define ERR_LOGGING_META_EXISTS			-2306
#define ERR_LOGGING_META_NOT_FOUND		-2307
#define ERR_LOGGING_UNKNOWN				-2308
#define ERR_LOGGING_EXPORT_NOT_FOUND	-2309
#define ERR_LOGGING_RESERVED			-2310
#define ERR_NLS_MESSAGE_NOT_FOUND		-2321

#define ERR_LOCKING_LOCKED				-2401 // Already locked.
#define ERR_LOCKING_UNLOCKED			-2402 // Already unlocked.

#define ERR_REFERENCE_ALL_LINKED		-2501 // Resource Referenced.
#define ERR_REFERENCE_SOME_LINKED		-2502 // Some resources referenced.
#define ERR_REFERENCE_UNKNOWN			-2503 // Unknown error.
#define ERR_REFERENCE_XML_WRITER		-2504
#define ERR_REFERENCE_NOT_FOUND			-2505

#define ERR_FILESYSTEM_FLUSH_FAIL		-2701
#define ERR_FILESYSTEM_REMOVE			-2702
#define ERR_FILESYSTEM_OPEN_FAIL		-2703
#define ERR_FILESYSTEM_TASK_NOT_FOUND	-2704
#define ERR_FILESYSTEM_XML_WRITER		-2705
#define ERR_FILESYSTEM_MOVE				-2706
#define ERR_FILESYSTEM_PROTECTED		-2707
#define ERR_FILESYSTEM_STAGING_STARTED	-2721
#define ERR_FILESYSTEM_STAGING_STOPPED	-2722
#define ERR_FILESYSTEM_IS_DIRECTORY		-2723
#define ERR_FILESYSTEM_STAGING_FULL		-2724
#define ERR_FILESYSTEM_EXPORT_SIZE		-2725
#define ERR_DISKWATCH_NOT_FOUND			-2731

#define ERR_NOTIFICATION_NOT_FOUND		-2801
#define ERR_NOTIFICATION_EXISTS			-2802
#define ERR_NOTIFICATION_BAD_XML		-2803
#define ERR_NOTIFICATION_NOT_INIT		-2804
#define ERR_NOTIFICATION_NOTSTOPPED		-2805
#define ERR_NOTIFICATION_NOTSTARTED		-2806
#define ERR_NOTIFICATION_UNKNOWN		-2807

#define ERR_ALERT_TYPE_INVALID			-2811

#define ERR_NETWORK_ACL_DEF_BAD			-2911
#define ERR_NETWORK_ACL_EXISTS			-2912
#define ERR_NETWORK_ACL_NOTFOUND		-2913
#define ERR_NETWORK_ACL_BAD_ADDR		-2914

#define ERR_EXPORT_EXISTS				-3001
#define ERR_EXPORT_NOT_FOUND			-3002
#define ERR_EXPORT_NOT_SUPPORTED		-3003
#define ERR_EXPORT_LIB_XML				-3004
#define ERR_EXPORT_FAILED				-3005
#define ERR_EXPORT_BAD_XML				-3006
#define ERR_EXPORT_SOME_FAILED			-3007

#define ERR_POOL_DEADLOCK				-3011
#define ERR_MUTEX_DEADLOCK				-3012

#define ERR_OS_NOT_IMPLEMENTED			-3101
#define ERR_OS_NOT_REG					-3102
#define ERR_OS_LIB_XML					-3103
#define ERR_OS_SYS_API					-3104
#define ERR_OS_BAD_TIME					-3105
#define ERR_OS_FILE_OPEN				-3106
#define ERR_OS_NETWORK_IN_PROGRESS		-3107
#define ERR_OS_NO_ADAPTER				-3108
#define ERR_OS_REGISTRY					-3109
#define ERR_OS_SYS_COMP_NAME			-3110
#define ERR_OS_WIN32_NETSH				-3111
#define ERR_TIMESYNC_FAILED				-3112
#define ERR_TIMESYNC_EMPTY				-3113
#define ERR_TIMESYNC_LOCKED				-3114
#define ERR_OS_NET_REBOOT_REQD			3115
#define ERR_OS_MEM_HIGH_USAGE			-3116
#define ERR_OS_TIMEZONE_REBOOT_REQD		3117
#define ERR_OS_REBOOT_REQD				3118
#define ERR_OS_NETWORK_SIZE_LIMIT		-3119
#define ERR_OS_REBOOT_IN_PROGRESS		-3120

/* -3131 to -3141 is reserved for linux error codes */

#define ERR_LICENSE_BAD_KEY 			-3201
#define ERR_LICENSE_EXISTS				-3202
#define ERR_LICENSE_UNKNOWN				-3203
#define ERR_LICENSE_FEATURE_NOT_FOUND 	-3204
#define ERR_LICENSE_PRODUCT_NOT_FOUND 	-3205
#define ERR_LICENSE_PRODUCT_EXISTS		-3206
#define ERR_LICENSE_FEATURE_EXISTS		-3207
#define ERR_LICENSE_UNLICENSED			-3208
#define ERR_LICENSE_NOT_EXISTS			-3209
#define ERR_LICENSE_LIMIT_REACHED		-3210

#define ERR_GENADMIN_TAB_NOT_FOUND		-3401
#define ERR_GENADMIN_BUTTON_NOT_FOUND	-3402
#define ERR_GENADMIN_CALLBACK_NOT_FOUND	-3403
#define ERR_GENADMIN_SELECTION_NOT_FOUND -3404

#endif /*DW_CORE_ERRORS_H_*/
