//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Chat.h
//  Source: idl/Chat.idl
//  Generated: Tue May 24 12:35:14 2016
//  OpenSplice 6.6.2p1
//  
//******************************************************************
#ifndef _CHAT_H_
#define _CHAT_H_

#include "sacpp_mapping.h"
#include "inc\semadds_export.h"


namespace Chat
{
   struct User;
   struct Messages;

   struct OS_SEMADDS_API User
   {
         DDS::String_mgr name;
         DDS::Long id;
   };

   typedef DDS_DCPSStruct_var < User> User_var;
   typedef DDS_DCPSStruct_out < User> User_out;

   struct OS_SEMADDS_API Messages
   {
         DDS::String_mgr Message;
         DDS::Long id;
   };

   typedef DDS_DCPSStruct_var < Messages> Messages_var;
   typedef DDS_DCPSStruct_out < Messages> Messages_out;
}




#undef OS_SEMADDS_API

#endif
