//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Chat.cpp
//  Source: idl/Chat.idl
//  Generated: Tue May 24 12:35:14 2016
//  OpenSplice 6.6.2p1
//  
//******************************************************************

#include "Chat.h"




