//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_namedQosTypesDcps.h
//  Source: dds_namedQosTypesDcps.idl
//  Generated: Wed Jan 14 13:42:49 2015
//  OpenSplice V6.5.0b5
//  
//******************************************************************
#ifndef _DDS_NAMEDQOSTYPESDCPS_H_
#define _DDS_NAMEDQOSTYPESDCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps_builtintopics.h"
#include "dds_dcps.h"
#include "dds_namedQosTypes.h"






#endif
