
#define HAVE_LIBXML_ENCODING_H
#define HAVE_LIBXML_XMLERROR_H
#define HAVE_LIBXML_XMLMEMORY_H
#define HAVE_LIBXML_PARSER_H
#define HAVE_LIBXML_XMLREADER_H
#define HAVE_LIBXML_XMLWRITER_H
#define HAVE_LIBXML_XMLVERSION_H
#define HAVE_LIBXML2

