//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_namedQosTypesDcps.h
//  Source: dds_namedQosTypesDcps.idl
//  Generated: Wed Feb 24 00:54:06 2016
//  OpenSplice 6.6.2p1
//  
//******************************************************************
#ifndef _DDS_NAMEDQOSTYPESDCPS_H_
#define _DDS_NAMEDQOSTYPESDCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "dds_dcps_builtintopics.h"
#include "dds_namedQosTypes.h"
#include "cpp_dcps_if.h"






#undef OS_API

#endif
