//----------------------------------------------------------------
//
//-- Filename: ils/stomp/errors.h
//
//-- Copyright: 2001-2013, ILS Technology, LLC
//
//----------------------------------------------------------------

#ifndef ILS_STOMP_ERRORS_H_
#define ILS_STOMP_ERRORS_H_

#define ERR_STOMP_CLIENT_CONNECTED		-7802
#define ERR_STOMP_CLIENT_NOT_CONNECTED	-7803
#define ERR_STOMP_BAD_URL				-7804
#define ERR_STOMP_UNKNOWN_PROTO			-7805
#define ERR_STOMP_PENDING_ITEM_EXISTS	-7806
#define ERR_STOMP_PENDING_ITEM_NOT_FOUND -7807
#define ERR_STOMP_BROKER_ERROR			-7808
#define ERR_STOMP_POOL_NOT_INIT			-7809

#define ERR_STOMP_FRAME_BAD_TYPE		-7811
#define ERR_STOMP_FRAME_BAD_FORMAT		-7812
#define ERR_STOMP_FRAME_TIMEOUT			-7813
#define ERR_STOMP_FRAME_HEARTBEAT		-7814
#define ERR_STOMP_FRAME_NO_NULL_TERM	-7815
#define ERR_STOMP_FRAME_BAD_LENGTH		-7816
#define ERR_STOMP_FRAME_BAD_LENGTH2		-7817

#define ERR_STOMP_MESSAGE_PURGED		-7821

#define ERR_STOMP_SUBSCRIPTION_EXISTS		-7831
#define ERR_STOMP_SUBSCRIPTION_NOT_FOUND	-7832

#define ERR_STOMP_COONNECT_ERROR			-7841

#define ERR_STOMP_DEBUG_ERROR				-7851

#if 0

#define ERR_STOMP_PROPERTY_NOT_FOUND		-7731
#define ERR_STOMP_PROPERTY_TYPE_MISMATCH	-7732
#define ERR_STOMP_MESSAGE_BAD_DEST		-7741
#define ERR_STOMP_MESSAGE_BAD_REPLYTO	-7742
#define ERR_STOMP_MARHALL_UTF8_NOT_SUPPORTED	-7743

#endif

#endif
