//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: semadds.cpp
//  Source: idl/semadds.idl
//  Generated: Thu Mar 03 11:45:33 2016
//  OpenSplice V6.5.0p1
//  
//******************************************************************

#include "semadds.h"




