/*
 *                         OpenSplice DDS
 *
 *   This software and documentation are Copyright 2006 to 2014 PrismTech
 *   Limited and its licensees. All rights reserved. See file:
 *
 *                     $OSPL_HOME/LICENSE
 *
 *   for full copyright notice and license terms.
 *
 */

module Chat {
	struct User{
		string name;
		long id;
	};
   #pragma keylist User id

	struct Messages{
		string Message;
		long id;
	};
   #pragma keylist Messages id
};
