//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_builtinTopicsDcps.h
//  Source: dds_builtinTopicsDcps.idl
//  Generated: Wed Jan 14 13:42:49 2015
//  OpenSplice V6.5.0b5
//  
//******************************************************************
#ifndef _DDS_BUILTINTOPICSDCPS_H_
#define _DDS_BUILTINTOPICSDCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "dds_builtinTopics.h"


namespace DDS
{

   class ParticipantBuiltinTopicDataTypeSupportInterface;

   typedef ParticipantBuiltinTopicDataTypeSupportInterface * ParticipantBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < ParticipantBuiltinTopicDataTypeSupportInterface> ParticipantBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < ParticipantBuiltinTopicDataTypeSupportInterface> ParticipantBuiltinTopicDataTypeSupportInterface_out;


   class ParticipantBuiltinTopicDataDataWriter;

   typedef ParticipantBuiltinTopicDataDataWriter * ParticipantBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < ParticipantBuiltinTopicDataDataWriter> ParticipantBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < ParticipantBuiltinTopicDataDataWriter> ParticipantBuiltinTopicDataDataWriter_out;


   class ParticipantBuiltinTopicDataDataReader;

   typedef ParticipantBuiltinTopicDataDataReader * ParticipantBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < ParticipantBuiltinTopicDataDataReader> ParticipantBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < ParticipantBuiltinTopicDataDataReader> ParticipantBuiltinTopicDataDataReader_out;


   class TopicBuiltinTopicDataTypeSupportInterface;

   typedef TopicBuiltinTopicDataTypeSupportInterface * TopicBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < TopicBuiltinTopicDataTypeSupportInterface> TopicBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < TopicBuiltinTopicDataTypeSupportInterface> TopicBuiltinTopicDataTypeSupportInterface_out;


   class TopicBuiltinTopicDataDataWriter;

   typedef TopicBuiltinTopicDataDataWriter * TopicBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < TopicBuiltinTopicDataDataWriter> TopicBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < TopicBuiltinTopicDataDataWriter> TopicBuiltinTopicDataDataWriter_out;


   class TopicBuiltinTopicDataDataReader;

   typedef TopicBuiltinTopicDataDataReader * TopicBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < TopicBuiltinTopicDataDataReader> TopicBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < TopicBuiltinTopicDataDataReader> TopicBuiltinTopicDataDataReader_out;


   class PublicationBuiltinTopicDataTypeSupportInterface;

   typedef PublicationBuiltinTopicDataTypeSupportInterface * PublicationBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < PublicationBuiltinTopicDataTypeSupportInterface> PublicationBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < PublicationBuiltinTopicDataTypeSupportInterface> PublicationBuiltinTopicDataTypeSupportInterface_out;


   class PublicationBuiltinTopicDataDataWriter;

   typedef PublicationBuiltinTopicDataDataWriter * PublicationBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < PublicationBuiltinTopicDataDataWriter> PublicationBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < PublicationBuiltinTopicDataDataWriter> PublicationBuiltinTopicDataDataWriter_out;


   class PublicationBuiltinTopicDataDataReader;

   typedef PublicationBuiltinTopicDataDataReader * PublicationBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < PublicationBuiltinTopicDataDataReader> PublicationBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < PublicationBuiltinTopicDataDataReader> PublicationBuiltinTopicDataDataReader_out;


   class SubscriptionBuiltinTopicDataTypeSupportInterface;

   typedef SubscriptionBuiltinTopicDataTypeSupportInterface * SubscriptionBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < SubscriptionBuiltinTopicDataTypeSupportInterface> SubscriptionBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < SubscriptionBuiltinTopicDataTypeSupportInterface> SubscriptionBuiltinTopicDataTypeSupportInterface_out;


   class SubscriptionBuiltinTopicDataDataWriter;

   typedef SubscriptionBuiltinTopicDataDataWriter * SubscriptionBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < SubscriptionBuiltinTopicDataDataWriter> SubscriptionBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < SubscriptionBuiltinTopicDataDataWriter> SubscriptionBuiltinTopicDataDataWriter_out;


   class SubscriptionBuiltinTopicDataDataReader;

   typedef SubscriptionBuiltinTopicDataDataReader * SubscriptionBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < SubscriptionBuiltinTopicDataDataReader> SubscriptionBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < SubscriptionBuiltinTopicDataDataReader> SubscriptionBuiltinTopicDataDataReader_out;


   class CMParticipantBuiltinTopicDataTypeSupportInterface;

   typedef CMParticipantBuiltinTopicDataTypeSupportInterface * CMParticipantBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < CMParticipantBuiltinTopicDataTypeSupportInterface> CMParticipantBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < CMParticipantBuiltinTopicDataTypeSupportInterface> CMParticipantBuiltinTopicDataTypeSupportInterface_out;


   class CMParticipantBuiltinTopicDataDataWriter;

   typedef CMParticipantBuiltinTopicDataDataWriter * CMParticipantBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < CMParticipantBuiltinTopicDataDataWriter> CMParticipantBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < CMParticipantBuiltinTopicDataDataWriter> CMParticipantBuiltinTopicDataDataWriter_out;


   class CMParticipantBuiltinTopicDataDataReader;

   typedef CMParticipantBuiltinTopicDataDataReader * CMParticipantBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < CMParticipantBuiltinTopicDataDataReader> CMParticipantBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < CMParticipantBuiltinTopicDataDataReader> CMParticipantBuiltinTopicDataDataReader_out;


   class CMPublisherBuiltinTopicDataTypeSupportInterface;

   typedef CMPublisherBuiltinTopicDataTypeSupportInterface * CMPublisherBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < CMPublisherBuiltinTopicDataTypeSupportInterface> CMPublisherBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < CMPublisherBuiltinTopicDataTypeSupportInterface> CMPublisherBuiltinTopicDataTypeSupportInterface_out;


   class CMPublisherBuiltinTopicDataDataWriter;

   typedef CMPublisherBuiltinTopicDataDataWriter * CMPublisherBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < CMPublisherBuiltinTopicDataDataWriter> CMPublisherBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < CMPublisherBuiltinTopicDataDataWriter> CMPublisherBuiltinTopicDataDataWriter_out;


   class CMPublisherBuiltinTopicDataDataReader;

   typedef CMPublisherBuiltinTopicDataDataReader * CMPublisherBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < CMPublisherBuiltinTopicDataDataReader> CMPublisherBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < CMPublisherBuiltinTopicDataDataReader> CMPublisherBuiltinTopicDataDataReader_out;


   class CMSubscriberBuiltinTopicDataTypeSupportInterface;

   typedef CMSubscriberBuiltinTopicDataTypeSupportInterface * CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < CMSubscriberBuiltinTopicDataTypeSupportInterface> CMSubscriberBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < CMSubscriberBuiltinTopicDataTypeSupportInterface> CMSubscriberBuiltinTopicDataTypeSupportInterface_out;


   class CMSubscriberBuiltinTopicDataDataWriter;

   typedef CMSubscriberBuiltinTopicDataDataWriter * CMSubscriberBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < CMSubscriberBuiltinTopicDataDataWriter> CMSubscriberBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < CMSubscriberBuiltinTopicDataDataWriter> CMSubscriberBuiltinTopicDataDataWriter_out;


   class CMSubscriberBuiltinTopicDataDataReader;

   typedef CMSubscriberBuiltinTopicDataDataReader * CMSubscriberBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < CMSubscriberBuiltinTopicDataDataReader> CMSubscriberBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < CMSubscriberBuiltinTopicDataDataReader> CMSubscriberBuiltinTopicDataDataReader_out;


   class CMDataWriterBuiltinTopicDataTypeSupportInterface;

   typedef CMDataWriterBuiltinTopicDataTypeSupportInterface * CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < CMDataWriterBuiltinTopicDataTypeSupportInterface> CMDataWriterBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < CMDataWriterBuiltinTopicDataTypeSupportInterface> CMDataWriterBuiltinTopicDataTypeSupportInterface_out;


   class CMDataWriterBuiltinTopicDataDataWriter;

   typedef CMDataWriterBuiltinTopicDataDataWriter * CMDataWriterBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < CMDataWriterBuiltinTopicDataDataWriter> CMDataWriterBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < CMDataWriterBuiltinTopicDataDataWriter> CMDataWriterBuiltinTopicDataDataWriter_out;


   class CMDataWriterBuiltinTopicDataDataReader;

   typedef CMDataWriterBuiltinTopicDataDataReader * CMDataWriterBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < CMDataWriterBuiltinTopicDataDataReader> CMDataWriterBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < CMDataWriterBuiltinTopicDataDataReader> CMDataWriterBuiltinTopicDataDataReader_out;


   class CMDataReaderBuiltinTopicDataTypeSupportInterface;

   typedef CMDataReaderBuiltinTopicDataTypeSupportInterface * CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < CMDataReaderBuiltinTopicDataTypeSupportInterface> CMDataReaderBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < CMDataReaderBuiltinTopicDataTypeSupportInterface> CMDataReaderBuiltinTopicDataTypeSupportInterface_out;


   class CMDataReaderBuiltinTopicDataDataWriter;

   typedef CMDataReaderBuiltinTopicDataDataWriter * CMDataReaderBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < CMDataReaderBuiltinTopicDataDataWriter> CMDataReaderBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < CMDataReaderBuiltinTopicDataDataWriter> CMDataReaderBuiltinTopicDataDataWriter_out;


   class CMDataReaderBuiltinTopicDataDataReader;

   typedef CMDataReaderBuiltinTopicDataDataReader * CMDataReaderBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < CMDataReaderBuiltinTopicDataDataReader> CMDataReaderBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < CMDataReaderBuiltinTopicDataDataReader> CMDataReaderBuiltinTopicDataDataReader_out;


   struct ParticipantBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < ParticipantBuiltinTopicData, struct ParticipantBuiltinTopicDataSeq_uniq_> ParticipantBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < ParticipantBuiltinTopicDataSeq> ParticipantBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < ParticipantBuiltinTopicDataSeq> ParticipantBuiltinTopicDataSeq_out;
   class ParticipantBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef ParticipantBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef ParticipantBuiltinTopicDataTypeSupportInterface_var _var_type;

      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _duplicate (ParticipantBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      ParticipantBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      ParticipantBuiltinTopicDataTypeSupportInterface () {};
      ~ParticipantBuiltinTopicDataTypeSupportInterface () {};
   private:
      ParticipantBuiltinTopicDataTypeSupportInterface (const ParticipantBuiltinTopicDataTypeSupportInterface &);
      ParticipantBuiltinTopicDataTypeSupportInterface & operator = (const ParticipantBuiltinTopicDataTypeSupportInterface &);
   };

   class ParticipantBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef ParticipantBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef ParticipantBuiltinTopicDataDataWriter_var _var_type;

      static ParticipantBuiltinTopicDataDataWriter_ptr _duplicate (ParticipantBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static ParticipantBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      ParticipantBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const ParticipantBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const ParticipantBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const ParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const ParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const ParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const ParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const ParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const ParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const ParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const ParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (ParticipantBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const ParticipantBuiltinTopicData& instance_data) = 0;

   protected:
      ParticipantBuiltinTopicDataDataWriter () {};
      ~ParticipantBuiltinTopicDataDataWriter () {};
   private:
      ParticipantBuiltinTopicDataDataWriter (const ParticipantBuiltinTopicDataDataWriter &);
      ParticipantBuiltinTopicDataDataWriter & operator = (const ParticipantBuiltinTopicDataDataWriter &);
   };

   class ParticipantBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef ParticipantBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef ParticipantBuiltinTopicDataDataReader_var _var_type;

      static ParticipantBuiltinTopicDataDataReader_ptr _duplicate (ParticipantBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static ParticipantBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      ParticipantBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (ParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (ParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (ParticipantBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const ParticipantBuiltinTopicData& instance) = 0;

   protected:
      ParticipantBuiltinTopicDataDataReader () {};
      ~ParticipantBuiltinTopicDataDataReader () {};
   private:
      ParticipantBuiltinTopicDataDataReader (const ParticipantBuiltinTopicDataDataReader &);
      ParticipantBuiltinTopicDataDataReader & operator = (const ParticipantBuiltinTopicDataDataReader &);
   };

   struct TopicBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < TopicBuiltinTopicData, struct TopicBuiltinTopicDataSeq_uniq_> TopicBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < TopicBuiltinTopicDataSeq> TopicBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < TopicBuiltinTopicDataSeq> TopicBuiltinTopicDataSeq_out;
   class TopicBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef TopicBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef TopicBuiltinTopicDataTypeSupportInterface_var _var_type;

      static TopicBuiltinTopicDataTypeSupportInterface_ptr _duplicate (TopicBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static TopicBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      TopicBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      TopicBuiltinTopicDataTypeSupportInterface () {};
      ~TopicBuiltinTopicDataTypeSupportInterface () {};
   private:
      TopicBuiltinTopicDataTypeSupportInterface (const TopicBuiltinTopicDataTypeSupportInterface &);
      TopicBuiltinTopicDataTypeSupportInterface & operator = (const TopicBuiltinTopicDataTypeSupportInterface &);
   };

   class TopicBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef TopicBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef TopicBuiltinTopicDataDataWriter_var _var_type;

      static TopicBuiltinTopicDataDataWriter_ptr _duplicate (TopicBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static TopicBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      TopicBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const TopicBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const TopicBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const TopicBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const TopicBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const TopicBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const TopicBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const TopicBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const TopicBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const TopicBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const TopicBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (TopicBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const TopicBuiltinTopicData& instance_data) = 0;

   protected:
      TopicBuiltinTopicDataDataWriter () {};
      ~TopicBuiltinTopicDataDataWriter () {};
   private:
      TopicBuiltinTopicDataDataWriter (const TopicBuiltinTopicDataDataWriter &);
      TopicBuiltinTopicDataDataWriter & operator = (const TopicBuiltinTopicDataDataWriter &);
   };

   class TopicBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef TopicBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef TopicBuiltinTopicDataDataReader_var _var_type;

      static TopicBuiltinTopicDataDataReader_ptr _duplicate (TopicBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static TopicBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      TopicBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (TopicBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (TopicBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (TopicBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const TopicBuiltinTopicData& instance) = 0;

   protected:
      TopicBuiltinTopicDataDataReader () {};
      ~TopicBuiltinTopicDataDataReader () {};
   private:
      TopicBuiltinTopicDataDataReader (const TopicBuiltinTopicDataDataReader &);
      TopicBuiltinTopicDataDataReader & operator = (const TopicBuiltinTopicDataDataReader &);
   };

   struct PublicationBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < PublicationBuiltinTopicData, struct PublicationBuiltinTopicDataSeq_uniq_> PublicationBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < PublicationBuiltinTopicDataSeq> PublicationBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < PublicationBuiltinTopicDataSeq> PublicationBuiltinTopicDataSeq_out;
   class PublicationBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef PublicationBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef PublicationBuiltinTopicDataTypeSupportInterface_var _var_type;

      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _duplicate (PublicationBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      PublicationBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      PublicationBuiltinTopicDataTypeSupportInterface () {};
      ~PublicationBuiltinTopicDataTypeSupportInterface () {};
   private:
      PublicationBuiltinTopicDataTypeSupportInterface (const PublicationBuiltinTopicDataTypeSupportInterface &);
      PublicationBuiltinTopicDataTypeSupportInterface & operator = (const PublicationBuiltinTopicDataTypeSupportInterface &);
   };

   class PublicationBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef PublicationBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef PublicationBuiltinTopicDataDataWriter_var _var_type;

      static PublicationBuiltinTopicDataDataWriter_ptr _duplicate (PublicationBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static PublicationBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      PublicationBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const PublicationBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const PublicationBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const PublicationBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const PublicationBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const PublicationBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const PublicationBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const PublicationBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const PublicationBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const PublicationBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const PublicationBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (PublicationBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const PublicationBuiltinTopicData& instance_data) = 0;

   protected:
      PublicationBuiltinTopicDataDataWriter () {};
      ~PublicationBuiltinTopicDataDataWriter () {};
   private:
      PublicationBuiltinTopicDataDataWriter (const PublicationBuiltinTopicDataDataWriter &);
      PublicationBuiltinTopicDataDataWriter & operator = (const PublicationBuiltinTopicDataDataWriter &);
   };

   class PublicationBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef PublicationBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef PublicationBuiltinTopicDataDataReader_var _var_type;

      static PublicationBuiltinTopicDataDataReader_ptr _duplicate (PublicationBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static PublicationBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      PublicationBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (PublicationBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (PublicationBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (PublicationBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const PublicationBuiltinTopicData& instance) = 0;

   protected:
      PublicationBuiltinTopicDataDataReader () {};
      ~PublicationBuiltinTopicDataDataReader () {};
   private:
      PublicationBuiltinTopicDataDataReader (const PublicationBuiltinTopicDataDataReader &);
      PublicationBuiltinTopicDataDataReader & operator = (const PublicationBuiltinTopicDataDataReader &);
   };

   struct SubscriptionBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < SubscriptionBuiltinTopicData, struct SubscriptionBuiltinTopicDataSeq_uniq_> SubscriptionBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < SubscriptionBuiltinTopicDataSeq> SubscriptionBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < SubscriptionBuiltinTopicDataSeq> SubscriptionBuiltinTopicDataSeq_out;
   class SubscriptionBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef SubscriptionBuiltinTopicDataTypeSupportInterface_var _var_type;

      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _duplicate (SubscriptionBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      SubscriptionBuiltinTopicDataTypeSupportInterface () {};
      ~SubscriptionBuiltinTopicDataTypeSupportInterface () {};
   private:
      SubscriptionBuiltinTopicDataTypeSupportInterface (const SubscriptionBuiltinTopicDataTypeSupportInterface &);
      SubscriptionBuiltinTopicDataTypeSupportInterface & operator = (const SubscriptionBuiltinTopicDataTypeSupportInterface &);
   };

   class SubscriptionBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef SubscriptionBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef SubscriptionBuiltinTopicDataDataWriter_var _var_type;

      static SubscriptionBuiltinTopicDataDataWriter_ptr _duplicate (SubscriptionBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static SubscriptionBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      SubscriptionBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const SubscriptionBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (SubscriptionBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const SubscriptionBuiltinTopicData& instance_data) = 0;

   protected:
      SubscriptionBuiltinTopicDataDataWriter () {};
      ~SubscriptionBuiltinTopicDataDataWriter () {};
   private:
      SubscriptionBuiltinTopicDataDataWriter (const SubscriptionBuiltinTopicDataDataWriter &);
      SubscriptionBuiltinTopicDataDataWriter & operator = (const SubscriptionBuiltinTopicDataDataWriter &);
   };

   class SubscriptionBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef SubscriptionBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef SubscriptionBuiltinTopicDataDataReader_var _var_type;

      static SubscriptionBuiltinTopicDataDataReader_ptr _duplicate (SubscriptionBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static SubscriptionBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      SubscriptionBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (SubscriptionBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (SubscriptionBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (SubscriptionBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const SubscriptionBuiltinTopicData& instance) = 0;

   protected:
      SubscriptionBuiltinTopicDataDataReader () {};
      ~SubscriptionBuiltinTopicDataDataReader () {};
   private:
      SubscriptionBuiltinTopicDataDataReader (const SubscriptionBuiltinTopicDataDataReader &);
      SubscriptionBuiltinTopicDataDataReader & operator = (const SubscriptionBuiltinTopicDataDataReader &);
   };

   struct CMParticipantBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < CMParticipantBuiltinTopicData, struct CMParticipantBuiltinTopicDataSeq_uniq_> CMParticipantBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < CMParticipantBuiltinTopicDataSeq> CMParticipantBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < CMParticipantBuiltinTopicDataSeq> CMParticipantBuiltinTopicDataSeq_out;
   class CMParticipantBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef CMParticipantBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef CMParticipantBuiltinTopicDataTypeSupportInterface_var _var_type;

      static CMParticipantBuiltinTopicDataTypeSupportInterface_ptr _duplicate (CMParticipantBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMParticipantBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static CMParticipantBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMParticipantBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      CMParticipantBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      CMParticipantBuiltinTopicDataTypeSupportInterface () {};
      ~CMParticipantBuiltinTopicDataTypeSupportInterface () {};
   private:
      CMParticipantBuiltinTopicDataTypeSupportInterface (const CMParticipantBuiltinTopicDataTypeSupportInterface &);
      CMParticipantBuiltinTopicDataTypeSupportInterface & operator = (const CMParticipantBuiltinTopicDataTypeSupportInterface &);
   };

   class CMParticipantBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef CMParticipantBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef CMParticipantBuiltinTopicDataDataWriter_var _var_type;

      static CMParticipantBuiltinTopicDataDataWriter_ptr _duplicate (CMParticipantBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMParticipantBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static CMParticipantBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMParticipantBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      CMParticipantBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const CMParticipantBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const CMParticipantBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const CMParticipantBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (CMParticipantBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMParticipantBuiltinTopicData& instance_data) = 0;

   protected:
      CMParticipantBuiltinTopicDataDataWriter () {};
      ~CMParticipantBuiltinTopicDataDataWriter () {};
   private:
      CMParticipantBuiltinTopicDataDataWriter (const CMParticipantBuiltinTopicDataDataWriter &);
      CMParticipantBuiltinTopicDataDataWriter & operator = (const CMParticipantBuiltinTopicDataDataWriter &);
   };

   class CMParticipantBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef CMParticipantBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef CMParticipantBuiltinTopicDataDataReader_var _var_type;

      static CMParticipantBuiltinTopicDataDataReader_ptr _duplicate (CMParticipantBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMParticipantBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static CMParticipantBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMParticipantBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      CMParticipantBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (CMParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (CMParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (CMParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (CMParticipantBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMParticipantBuiltinTopicData& instance) = 0;

   protected:
      CMParticipantBuiltinTopicDataDataReader () {};
      ~CMParticipantBuiltinTopicDataDataReader () {};
   private:
      CMParticipantBuiltinTopicDataDataReader (const CMParticipantBuiltinTopicDataDataReader &);
      CMParticipantBuiltinTopicDataDataReader & operator = (const CMParticipantBuiltinTopicDataDataReader &);
   };

   struct CMPublisherBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < CMPublisherBuiltinTopicData, struct CMPublisherBuiltinTopicDataSeq_uniq_> CMPublisherBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < CMPublisherBuiltinTopicDataSeq> CMPublisherBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < CMPublisherBuiltinTopicDataSeq> CMPublisherBuiltinTopicDataSeq_out;
   class CMPublisherBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef CMPublisherBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef CMPublisherBuiltinTopicDataTypeSupportInterface_var _var_type;

      static CMPublisherBuiltinTopicDataTypeSupportInterface_ptr _duplicate (CMPublisherBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMPublisherBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static CMPublisherBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMPublisherBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      CMPublisherBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      CMPublisherBuiltinTopicDataTypeSupportInterface () {};
      ~CMPublisherBuiltinTopicDataTypeSupportInterface () {};
   private:
      CMPublisherBuiltinTopicDataTypeSupportInterface (const CMPublisherBuiltinTopicDataTypeSupportInterface &);
      CMPublisherBuiltinTopicDataTypeSupportInterface & operator = (const CMPublisherBuiltinTopicDataTypeSupportInterface &);
   };

   class CMPublisherBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef CMPublisherBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef CMPublisherBuiltinTopicDataDataWriter_var _var_type;

      static CMPublisherBuiltinTopicDataDataWriter_ptr _duplicate (CMPublisherBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMPublisherBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static CMPublisherBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMPublisherBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      CMPublisherBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const CMPublisherBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const CMPublisherBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const CMPublisherBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (CMPublisherBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMPublisherBuiltinTopicData& instance_data) = 0;

   protected:
      CMPublisherBuiltinTopicDataDataWriter () {};
      ~CMPublisherBuiltinTopicDataDataWriter () {};
   private:
      CMPublisherBuiltinTopicDataDataWriter (const CMPublisherBuiltinTopicDataDataWriter &);
      CMPublisherBuiltinTopicDataDataWriter & operator = (const CMPublisherBuiltinTopicDataDataWriter &);
   };

   class CMPublisherBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef CMPublisherBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef CMPublisherBuiltinTopicDataDataReader_var _var_type;

      static CMPublisherBuiltinTopicDataDataReader_ptr _duplicate (CMPublisherBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMPublisherBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static CMPublisherBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMPublisherBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      CMPublisherBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (CMPublisherBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (CMPublisherBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (CMPublisherBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (CMPublisherBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMPublisherBuiltinTopicData& instance) = 0;

   protected:
      CMPublisherBuiltinTopicDataDataReader () {};
      ~CMPublisherBuiltinTopicDataDataReader () {};
   private:
      CMPublisherBuiltinTopicDataDataReader (const CMPublisherBuiltinTopicDataDataReader &);
      CMPublisherBuiltinTopicDataDataReader & operator = (const CMPublisherBuiltinTopicDataDataReader &);
   };

   struct CMSubscriberBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < CMSubscriberBuiltinTopicData, struct CMSubscriberBuiltinTopicDataSeq_uniq_> CMSubscriberBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < CMSubscriberBuiltinTopicDataSeq> CMSubscriberBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < CMSubscriberBuiltinTopicDataSeq> CMSubscriberBuiltinTopicDataSeq_out;
   class CMSubscriberBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef CMSubscriberBuiltinTopicDataTypeSupportInterface_var _var_type;

      static CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr _duplicate (CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      CMSubscriberBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      CMSubscriberBuiltinTopicDataTypeSupportInterface () {};
      ~CMSubscriberBuiltinTopicDataTypeSupportInterface () {};
   private:
      CMSubscriberBuiltinTopicDataTypeSupportInterface (const CMSubscriberBuiltinTopicDataTypeSupportInterface &);
      CMSubscriberBuiltinTopicDataTypeSupportInterface & operator = (const CMSubscriberBuiltinTopicDataTypeSupportInterface &);
   };

   class CMSubscriberBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef CMSubscriberBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef CMSubscriberBuiltinTopicDataDataWriter_var _var_type;

      static CMSubscriberBuiltinTopicDataDataWriter_ptr _duplicate (CMSubscriberBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMSubscriberBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static CMSubscriberBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMSubscriberBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      CMSubscriberBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const CMSubscriberBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const CMSubscriberBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const CMSubscriberBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (CMSubscriberBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMSubscriberBuiltinTopicData& instance_data) = 0;

   protected:
      CMSubscriberBuiltinTopicDataDataWriter () {};
      ~CMSubscriberBuiltinTopicDataDataWriter () {};
   private:
      CMSubscriberBuiltinTopicDataDataWriter (const CMSubscriberBuiltinTopicDataDataWriter &);
      CMSubscriberBuiltinTopicDataDataWriter & operator = (const CMSubscriberBuiltinTopicDataDataWriter &);
   };

   class CMSubscriberBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef CMSubscriberBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef CMSubscriberBuiltinTopicDataDataReader_var _var_type;

      static CMSubscriberBuiltinTopicDataDataReader_ptr _duplicate (CMSubscriberBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMSubscriberBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static CMSubscriberBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMSubscriberBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      CMSubscriberBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (CMSubscriberBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (CMSubscriberBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (CMSubscriberBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (CMSubscriberBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMSubscriberBuiltinTopicData& instance) = 0;

   protected:
      CMSubscriberBuiltinTopicDataDataReader () {};
      ~CMSubscriberBuiltinTopicDataDataReader () {};
   private:
      CMSubscriberBuiltinTopicDataDataReader (const CMSubscriberBuiltinTopicDataDataReader &);
      CMSubscriberBuiltinTopicDataDataReader & operator = (const CMSubscriberBuiltinTopicDataDataReader &);
   };

   struct CMDataWriterBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < CMDataWriterBuiltinTopicData, struct CMDataWriterBuiltinTopicDataSeq_uniq_> CMDataWriterBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < CMDataWriterBuiltinTopicDataSeq> CMDataWriterBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < CMDataWriterBuiltinTopicDataSeq> CMDataWriterBuiltinTopicDataSeq_out;
   class CMDataWriterBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef CMDataWriterBuiltinTopicDataTypeSupportInterface_var _var_type;

      static CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr _duplicate (CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      CMDataWriterBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      CMDataWriterBuiltinTopicDataTypeSupportInterface () {};
      ~CMDataWriterBuiltinTopicDataTypeSupportInterface () {};
   private:
      CMDataWriterBuiltinTopicDataTypeSupportInterface (const CMDataWriterBuiltinTopicDataTypeSupportInterface &);
      CMDataWriterBuiltinTopicDataTypeSupportInterface & operator = (const CMDataWriterBuiltinTopicDataTypeSupportInterface &);
   };

   class CMDataWriterBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef CMDataWriterBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef CMDataWriterBuiltinTopicDataDataWriter_var _var_type;

      static CMDataWriterBuiltinTopicDataDataWriter_ptr _duplicate (CMDataWriterBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMDataWriterBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static CMDataWriterBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMDataWriterBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      CMDataWriterBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const CMDataWriterBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const CMDataWriterBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const CMDataWriterBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (CMDataWriterBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMDataWriterBuiltinTopicData& instance_data) = 0;

   protected:
      CMDataWriterBuiltinTopicDataDataWriter () {};
      ~CMDataWriterBuiltinTopicDataDataWriter () {};
   private:
      CMDataWriterBuiltinTopicDataDataWriter (const CMDataWriterBuiltinTopicDataDataWriter &);
      CMDataWriterBuiltinTopicDataDataWriter & operator = (const CMDataWriterBuiltinTopicDataDataWriter &);
   };

   class CMDataWriterBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef CMDataWriterBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef CMDataWriterBuiltinTopicDataDataReader_var _var_type;

      static CMDataWriterBuiltinTopicDataDataReader_ptr _duplicate (CMDataWriterBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMDataWriterBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static CMDataWriterBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMDataWriterBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      CMDataWriterBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (CMDataWriterBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (CMDataWriterBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (CMDataWriterBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (CMDataWriterBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMDataWriterBuiltinTopicData& instance) = 0;

   protected:
      CMDataWriterBuiltinTopicDataDataReader () {};
      ~CMDataWriterBuiltinTopicDataDataReader () {};
   private:
      CMDataWriterBuiltinTopicDataDataReader (const CMDataWriterBuiltinTopicDataDataReader &);
      CMDataWriterBuiltinTopicDataDataReader & operator = (const CMDataWriterBuiltinTopicDataDataReader &);
   };

   struct CMDataReaderBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < CMDataReaderBuiltinTopicData, struct CMDataReaderBuiltinTopicDataSeq_uniq_> CMDataReaderBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < CMDataReaderBuiltinTopicDataSeq> CMDataReaderBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < CMDataReaderBuiltinTopicDataSeq> CMDataReaderBuiltinTopicDataSeq_out;
   class CMDataReaderBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef CMDataReaderBuiltinTopicDataTypeSupportInterface_var _var_type;

      static CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr _duplicate (CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      CMDataReaderBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      CMDataReaderBuiltinTopicDataTypeSupportInterface () {};
      ~CMDataReaderBuiltinTopicDataTypeSupportInterface () {};
   private:
      CMDataReaderBuiltinTopicDataTypeSupportInterface (const CMDataReaderBuiltinTopicDataTypeSupportInterface &);
      CMDataReaderBuiltinTopicDataTypeSupportInterface & operator = (const CMDataReaderBuiltinTopicDataTypeSupportInterface &);
   };

   class CMDataReaderBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef CMDataReaderBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef CMDataReaderBuiltinTopicDataDataWriter_var _var_type;

      static CMDataReaderBuiltinTopicDataDataWriter_ptr _duplicate (CMDataReaderBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMDataReaderBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static CMDataReaderBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMDataReaderBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      CMDataReaderBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual ULongLong register_instance (const CMDataReaderBuiltinTopicData& instance_data) = 0;
      virtual ULongLong register_instance_w_timestamp (const CMDataReaderBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long write_w_timestamp (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long dispose_w_timestamp (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const CMDataReaderBuiltinTopicData& instance_data, ULongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (CMDataReaderBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMDataReaderBuiltinTopicData& instance_data) = 0;

   protected:
      CMDataReaderBuiltinTopicDataDataWriter () {};
      ~CMDataReaderBuiltinTopicDataDataWriter () {};
   private:
      CMDataReaderBuiltinTopicDataDataWriter (const CMDataReaderBuiltinTopicDataDataWriter &);
      CMDataReaderBuiltinTopicDataDataWriter & operator = (const CMDataReaderBuiltinTopicDataDataWriter &);
   };

   class CMDataReaderBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef CMDataReaderBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef CMDataReaderBuiltinTopicDataDataReader_var _var_type;

      static CMDataReaderBuiltinTopicDataDataReader_ptr _duplicate (CMDataReaderBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static CMDataReaderBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static CMDataReaderBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static CMDataReaderBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      CMDataReaderBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (CMDataReaderBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (CMDataReaderBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (CMDataReaderBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (CMDataReaderBuiltinTopicData& key_holder, ULongLong handle) = 0;
      virtual ULongLong lookup_instance (const CMDataReaderBuiltinTopicData& instance) = 0;

   protected:
      CMDataReaderBuiltinTopicDataDataReader () {};
      ~CMDataReaderBuiltinTopicDataDataReader () {};
   private:
      CMDataReaderBuiltinTopicDataDataReader (const CMDataReaderBuiltinTopicDataDataReader &);
      CMDataReaderBuiltinTopicDataDataReader & operator = (const CMDataReaderBuiltinTopicDataDataReader &);
   };
}

#endif
